### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings

### ISSUE THREAD

**Issue by xcybermanx** [YarmolenkoD/notpixel#1]
(venv) C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel>python main.py
Traceback (most recent call last):
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\bot\config\config.py", line 29, in <module>
    settings = Settings()
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\venv\lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel\venv\lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
enable_auto_task
  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden

(venv) C:\Users\x\Desktop\bot_carte_yahia\carta2\notpixel>

**Comment by xcybermanx** [comment]
> @xcybermanx Thanks for feedback, will fix it

Thank you for your kind words & your Hard Work

**Comment by YarmolenkoD** [comment]
@xcybermanx please update your .env file and make it like this please:

API_ID=
API_HASH=

USE_REF=
REF_ID=

USE_RANDOM_DELAY_IN_RUN=
RANDOM_DELAY_IN_RUN=

SLEEP_TIME_IN_MINUTES=

ENABLE_AUTO_TASKS=
ENABLE_AUTO_DRAW=
ENABLE_JOIN_TG_CHANNELS=
ENABLE_CLAIM_REWARD=
ENABLE_AUTO_UPGRADE=

BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=

USE_PROXY_FROM_FILE=

**Comment by YarmolenkoD** [comment]
@xcybermanx Also add values for API_ID and API_HASH because this is required. 

And put star to repository please :)

**Comment by s10ringleader** [comment]
BOOSTS_BLACK_LIST=
TASKS_TODO_LIST=
what i must put here?

**Comment by xcybermanx** [comment]
> @xcybermanx Also add values for API_ID and API_HASH because this is required.
> 
> And put star to repository please :)

worked thank i am 2eme person to make star :)
