### ISSUE TITLE
Ошибка при установке TgCrypto

### ISSUE THREAD

**Issue by mollyxs** [YarmolenkoD/notpixel#11]
```
Building wheels for collected packages: TgCrypto
  Building wheel for TgCrypto (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for TgCrypto (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      C:\Users\Administrator\AppData\Local\Temp\pip-build-env-6ki63y23\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-312\tests
      copying tests\__init__.py -> build\lib.win-amd64-cpython-312\tests
      creating build\lib.win-amd64-cpython-312\tests\cbc
      copying tests\cbc\test_cbc.py -> build\lib.win-amd64-cpython-312\tests\cbc
      copying tests\cbc\__init__.py -> build\lib.win-amd64-cpython-312\tests\cbc
      creating build\lib.win-amd64-cpython-312\tests\ctr
      copying tests\ctr\test_ctr.py -> build\lib.win-amd64-cpython-312\tests\ctr
      copying tests\ctr\__init__.py -> build\lib.win-amd64-cpython-312\tests\ctr
      creating build\lib.win-amd64-cpython-312\tests\ige
      copying tests\ige\test_ige.py -> build\lib.win-amd64-cpython-312\tests\ige
      copying tests\ige\__init__.py -> build\lib.win-amd64-cpython-312\tests\ige
      running build_ext
      building 'tgcrypto' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TgCrypto
Failed to build TgCrypto
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (TgCrypto)
Copying configuration file
Скопировано файлов:         1.
"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Starting the bot...
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\notpixel-master\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Users\Administrator\Downloads\notpixel-master\bot\utils\__init__.py", line 1, in <module>
    from .logger import logger, info, warning, debug, success, error, critical
  File "c:\Users\Administrator\Downloads\notpixel-master\bot\utils\logger.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
done
PLEASE EDIT .ENV FILE
Для продолжения нажмите любую клавишу . . .
```
Устанавливал Microsoft Visual C++ 14.0, не помогло

**Comment by YarmolenkoD** [comment]
@mollyxs Will fix it, thanks for feedback

**Comment by YarmolenkoD** [comment]
@mollyxs You need to install GIT on your computer

**Comment by YarmolenkoD** [comment]
@mollyxs Follow instructions for windows https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by mollyxs** [comment]
> @mollyxs Follow instructions for windows https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Я пофиксил. Оказывается tgcrypto работает только до версии 3.11, у меня 3.12 была.

**Comment by YarmolenkoD** [comment]
@mollyxs Спасибо за фидбек
