### ISSUE TITLE
what's this 

### ISSUE THREAD

**Issue by kholiqsantosa** [YarmolenkoD/notpixel#16]
![Screenshot_2024-09-29-20-40-38-408_com server auditor ssh client~2](https://github.com/user-attachments/assets/92621de6-2e14-4d57-a0ba-3a5645c5f372)

```
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]: Task exception was never retrieved
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]: future: <Task finished name='Task-1982' coro=<Client.handle_updates() done, defined at /root/notpixel/venv/lib/python3.10/site-packages/pyrogram/client.py:535> exception=ProgrammingError('Cannot operate on a closed database.')>
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]: Traceback (most recent call last):
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:   File "/root/notpixel/venv/lib/python3.10/site-packages/pyrogram/client.py", line 540, in handle_updates
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:     await self.fetch_peers(updates.users),
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:   File "/root/notpixel/venv/lib/python3.10/site-packages/pyrogram/client.py", line 531, in fetch_peers
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:     await self.storage.update_peers(parsed_peers)
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:   File "/root/notpixel/venv/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 129, in update_peers
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]:     self.conn.executemany(
Sep 29 20:33:40 iZk1a4u9nn9ex3l03z3ps5Z python3[50012]: sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by YarmolenkoD** [comment]
@kholiqsantosa Is this error still valid ?

If so, I think the problem may be in the session itself.
