### ISSUE TITLE
 Unsupported proxy forma

### ISSUE THREAD

**Issue by salamhbo048** [YarmolenkoD/notpixel#32]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\main.py", line 8, in main
    await process()
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\bot\utils\launcher.py", line 89, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\bot\utils\launcher.py", line 53, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\bot\utils\launcher.py", line 53, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "C:\Users\Administrator\Desktop\bots\notpixel-master\venv\lib\site-packages\better_proxy\proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: type://user:pass@ip:port
done
PLEASE EDIT .ENV FILE
Press any key to continue . . .

**Comment by kholiqsantosa** [comment]
probably you put "true" for "use proxy from file" in the .env file, but didn’t drop your proxy in the bot/config folder.

**Comment by kumarKG** [comment]
most probably he did not put proxy type. write proxy type before cridential. for example http://ip:port:user:pass or socks5://ip:port:user:pass
