### ISSUE TITLE
No module named 'better_proxy'

### ISSUE THREAD

**Issue by the-pesar** [YarmolenkoD/notpixel#40]
Why???

```python
~/notpixel# sudo bash run.sh
Activating virtual environment...
run.sh: line 9: venv/bin/activate: No such file or directory
Dependencies already installed, skipping installation.
Skipping .env copying
Reinitialized existing Git repository in /root/notpixel/.git/
error: remote origin already exists.
No local changes to save
Already up to date.
No stash entries found.
Starting the bot...
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "/root/notpixel/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/notpixel/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/notpixel/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'
done
PLEASE EDIT .ENV FILE
```

**Comment by HoyT6yK** [comment]
`pip3 install -r requirements.txt` in the bot folder

**Comment by the-pesar** [comment]
> Use `source venv/bin/activate` and `pip3 install -r requirements.txt` in the bot folder

to run `source venv/bin/activate` i got:
```sh
-bash: venv/bin/activate: No such file or directory
```

**Comment by the-pesar** [comment]
> Use `source venv/bin/activate` and `pip3 install -r requirements.txt` in the bot folder

I solved previous error, and now i got:
```python
(venv) root@yasha:~/notpixel# python3.10 main.py --action
Traceback (most recent call last):
  File "/root/notpixel/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/notpixel/main.py", line 8, in main
    await process()
  File "/root/notpixel/bot/utils/launcher.py", line 89, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
  File "/root/notpixel/bot/utils/launcher.py", line 53, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/root/notpixel/bot/utils/launcher.py", line 53, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "/root/notpixel/venv/lib/python3.10/site-packages/better_proxy/proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: type://user:pass@ip:port

```

**Comment by HoyT6yK** [comment]
You either have the wrong proxy format or they are simply not specified. If you don't use a proxy, write in .env `USE_PROXY_FROM_FILE=False`

**Comment by YarmolenkoD** [comment]
@HoyT6yK Thanks for replying! 

@the-pesar Have you solved this problem?
