### ISSUE TITLE
Key error 3

### ISSUE THREAD

**Issue by MeoBeoTuTien** [YarmolenkoD/notpixel#63]
![Screenshot_2024-10-15-00-13-31-100_com.termux-edit.jpg](https://github.com/user-attachments/assets/fcbb9819-b42c-4e94-abf5-e80edce6a755)

Traceback (most recent call last):
  File "/storage/emulated/0/Download/not/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/storage/emulated/0/Download/not/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/storage/emulated/0/Download/not/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/storage/emulated/0/Download/not/bot/core/tapper.py", line 13, in <module>
    from aiocfscrape import CloudflareScraper
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by YarmolenkoD** [comment]
@MeoBeoTuTien Your version is 3.12
