### ISSUE TITLE
error

### ISSUE THREAD

**Issue by salehiparviz** [YarmolenkoD/notpixel#78]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/notpixel/bot/utils/__init__.py", line 1, in <module>
    from .logger import logger, info, warning, debug, success, error, critical
  File "/root/notpixel/bot/utils/logger.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by 1573712107** [comment]
pip install loguru

**Comment by YarmolenkoD** [comment]
@salehiparviz Yes, you need run pip install loguru or pip install -r requirements.txt

**Comment by salehiparviz** [comment]
> @salehiparviz Yes, you need run pip install loguru or pip install -r requirements.txt

Traceback (most recent call last):
  File "D:\python\921\notpixel\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\saleh\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\saleh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\python\921\notpixel\main.py", line 8, in main
    await process()
  File "D:\python\921\notpixel\bot\utils\launcher.py", line 95, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
  File "D:\python\921\notpixel\bot\utils\launcher.py", line 59, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "D:\python\921\notpixel\bot\utils\launcher.py", line 59, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
  File "D:\python\921\notpixel\venv\lib\site-packages\better_proxy\proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')
ValueError: Unsupported proxy format: type://user:pass@ip:port

**Comment by YarmolenkoD** [comment]
@salehiparviz Looks like you need to write correct proxy format in /bot/config/proxies.txt file.

EXAMPLE: 
http://username:pass@45.141.81.229:1111
http://username:pass@45.141.81.229:1111

Or if you have less than 3 accounts you can add this option in .env file
USE_PROXY_FROM_FILE=False (It will off proxy)

**Comment by salehiparviz** [comment]
> http://username:pass@

Unable to connect due to network issues: Error connecting to HTTP proxy 38.15
