### ISSUE TITLE
Cant install requirements and start bot

### ISSUE THREAD

**Issue by Nekspsy** [YarmolenkoD/notpixel#99]
Help please (можно на русском)

```
(venv) C:\PortableSort\NotPixel-Yarmolenko\notpixel>pip3 install -r requirements.txt
Collecting aiocfscrape==1.0.0 (from -r requirements.txt (line 1))
  Using cached aiocfscrape-1.0.0-py3-none-any.whl
Collecting aiohttp==3.9.3 (from -r requirements.txt (line 2))
  Using cached aiohttp-3.9.3-cp313-cp313-win_amd64.whl
Collecting aiohttp-proxy==0.1.2 (from -r requirements.txt (line 3))
  Using cached aiohttp_proxy-0.1.2-py3-none-any.whl.metadata (2.7 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 4))
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting annotated-types==0.6.0 (from -r requirements.txt (line 5))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting async-timeout==4.0.3 (from -r requirements.txt (line 6))
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 7))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 8))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting better-proxy==1.1.5 (from -r requirements.txt (line 9))
  Using cached better_proxy-1.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting Brotli==1.1.0 (from -r requirements.txt (line 10))
  Using cached Brotli-1.1.0-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Collecting centrifuge-python==0.3.1 (from -r requirements.txt (line 11))
  Using cached centrifuge_python-0.3.1-py3-none-any.whl.metadata (6.3 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 12))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting DateTime==5.5 (from -r requirements.txt (line 13))
  Using cached DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting fake-useragent==1.5.1 (from -r requirements.txt (line 14))
  Using cached fake_useragent-1.5.1-py3-none-any.whl.metadata (15 kB)
Collecting Faker==29.0.0 (from -r requirements.txt (line 15))
  Using cached Faker-29.0.0-py3-none-any.whl.metadata (15 kB)
Collecting frozenlist==1.4.1 (from -r requirements.txt (line 16))
  Using cached frozenlist-1.4.1-py3-none-any.whl.metadata (12 kB)
Collecting idna==3.6 (from -r requirements.txt (line 17))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting Js2Py==0.74 (from -r requirements.txt (line 18))
  Using cached Js2Py-0.74-py3-none-any.whl.metadata (868 bytes)
Collecting loguru==0.7.2 (from -r requirements.txt (line 19))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting multidict==6.0.5 (from -r requirements.txt (line 20))
  Using cached multidict-6.0.5-py3-none-any.whl.metadata (4.2 kB)
Collecting pillow==10.4.0 (from -r requirements.txt (line 21))
  Using cached pillow-10.4.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting protobuf==4.25.5 (from -r requirements.txt (line 22))
  Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Collecting pyaes==1.6.1 (from -r requirements.txt (line 23))
  Using cached pyaes-1.6.1-py3-none-any.whl
Collecting pycryptodome==3.20.0 (from -r requirements.txt (line 24))
  Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting pydantic==2.6.4 (from -r requirements.txt (line 25))
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Collecting pydantic-settings==2.2.1 (from -r requirements.txt (line 26))
  Using cached pydantic_settings-2.2.1-py3-none-any.whl.metadata (3.1 kB)
Collecting pydantic_core==2.16.3 (from -r requirements.txt (line 27))
  Using cached pydantic_core-2.16.3.tar.gz (368 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyjsparser==2.7.1 (from -r requirements.txt (line 28))
  Using cached pyjsparser-2.7.1-py3-none-any.whl
Collecting Pyrogram==2.0.106 (from -r requirements.txt (line 29))
  Using cached Pyrogram-2.0.106-py3-none-any.whl.metadata (4.4 kB)
Collecting PySocks==1.7.1 (from -r requirements.txt (line 30))
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting python-dateutil==2.9.0.post0 (from -r requirements.txt (line 31))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting python-dotenv==1.0.1 (from -r requirements.txt (line 32))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting pytz==2024.1 (from -r requirements.txt (line 33))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting six==1.16.0 (from -r requirements.txt (line 34))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting soupsieve==2.5 (from -r requirements.txt (line 35))
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting TgCrypto==1.2.5 (from -r requirements.txt (line 36))
  Using cached TgCrypto-1.2.5-cp313-cp313-win_amd64.whl
Collecting typing_extensions==4.11.0 (from -r requirements.txt (line 37))
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting tzdata==2024.1 (from -r requirements.txt (line 38))
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting tzlocal==5.2 (from -r requirements.txt (line 39))
  Using cached tzlocal-5.2-py3-none-any.whl.metadata (7.8 kB)
Collecting websockets==11.0.3 (from -r requirements.txt (line 40))
  Using cached websockets-11.0.3-py3-none-any.whl.metadata (6.6 kB)
Collecting win32-setctime==1.1.0 (from -r requirements.txt (line 41))
  Using cached win32_setctime-1.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting yarl==1.9.4 (from -r requirements.txt (line 42))
  Using cached yarl-1.9.4-py3-none-any.whl.metadata (31 kB)
Collecting zope.interface==6.4.post2 (from -r requirements.txt (line 43))
  Using cached zope.interface-6.4.post2-cp313-cp313-win_amd64.whl
Collecting setuptools (from zope.interface==6.4.post2->-r requirements.txt (line 43))
  Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
Using cached aiohttp_proxy-0.1.2-py3-none-any.whl (12 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached better_proxy-1.1.5-py3-none-any.whl (3.2 kB)
Using cached Brotli-1.1.0-cp313-cp313-win_amd64.whl (358 kB)
Using cached centrifuge_python-0.3.1-py3-none-any.whl (25 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached DateTime-5.5-py3-none-any.whl (52 kB)
Using cached fake_useragent-1.5.1-py3-none-any.whl (17 kB)
Using cached Faker-29.0.0-py3-none-any.whl (1.8 MB)
Using cached frozenlist-1.4.1-py3-none-any.whl (11 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached Js2Py-0.74-py3-none-any.whl (1.0 MB)
Using cached loguru-0.7.2-py3-none-any.whl (62 kB)
Using cached multidict-6.0.5-py3-none-any.whl (9.7 kB)
Using cached pillow-10.4.0-cp313-cp313-win_amd64.whl (2.6 MB)
Using cached protobuf-4.25.5-cp310-abi3-win_amd64.whl (413 kB)
Using cached pycryptodome-3.20.0-cp35-abi3-win_amd64.whl (1.8 MB)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Using cached Pyrogram-2.0.106-py3-none-any.whl (3.6 MB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Using cached websockets-11.0.3-py3-none-any.whl (118 kB)
Using cached win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Using cached yarl-1.9.4-py3-none-any.whl (31 kB)
Using cached setuptools-75.2.0-py3-none-any.whl (1.2 MB)
Building wheels for collected packages: pydantic_core
  Building wheel for pydantic_core (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pydantic_core (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      Running `maturin pep517 build-wheel -i C:\PortableSort\NotPixel-Yarmolenko\notpixel\venv\Scripts\python.exe --compatibility off`
      рџ“¦ Including license file "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\LICENSE"
      рџЌ№ Building a mixed python/rust project
      рџ”— Found pyo3 bindings
      рџђЌ Found CPython 3.13 at C:\PortableSort\NotPixel-Yarmolenko\notpixel\venv\Scripts\python.exe
      рџ“Ў Using build options features, bindings from pyproject.toml
         Compiling autocfg v1.1.0
         Compiling proc-macro2 v1.0.76
         Compiling target-lexicon v0.12.9
         Compiling unicode-ident v1.0.10
         Compiling cc v1.0.79
         Compiling once_cell v1.18.0
         Compiling cfg-if v1.0.0
         Compiling version_check v0.9.4
         Compiling quote v1.0.35
         Compiling python3-dll-a v0.2.9
         Compiling syn v2.0.48
         Compiling static_assertions v1.1.0
         Compiling windows_x86_64_msvc v0.48.0
         Compiling heck v0.4.1
         Compiling lexical-util v0.8.5
         Compiling ahash v0.8.7
         Compiling num-traits v0.2.16
         Compiling pyo3-build-config v0.20.2
         Compiling getrandom v0.2.10
         Compiling num-integer v0.1.45
         Compiling lock_api v0.4.10
         Compiling parking_lot_core v0.9.8
         Compiling zerocopy v0.7.32
         Compiling libc v0.2.147
         Compiling rustversion v1.0.13
         Compiling pyo3-ffi v0.20.2
         Compiling windows-targets v0.48.1
         Compiling memoffset v0.9.0
         Compiling num-bigint v0.4.4
         Compiling scopeguard v1.1.0
         Compiling smallvec v1.11.2
         Compiling tinyvec_macros v0.1.1
         Compiling allocator-api2 v0.2.16
         Compiling tinyvec v1.6.0
         Compiling hashbrown v0.14.3
         Compiling pyo3-macros-backend v0.20.2
         Compiling pyo3 v0.20.2
         Compiling lexical-write-integer v0.8.5
         Compiling lexical-parse-integer v0.8.6
         Compiling serde v1.0.195
         Compiling memchr v2.6.3
         Compiling lexical-parse-float v0.8.5
         Compiling strum_macros v0.25.3
         Compiling aho-corasick v1.0.2
         Compiling serde_derive v1.0.195
         Compiling lexical-write-float v0.8.5
         Compiling pyo3-macros v0.20.2
         Compiling parking_lot v0.12.1
         Compiling unicode-normalization v0.1.22
         Compiling indoc v2.0.4
         Compiling unicode-bidi v0.3.13
         Compiling unindent v0.2.3
         Compiling percent-encoding v2.3.1
         Compiling equivalent v1.0.1
         Compiling regex-syntax v0.8.2
         Compiling serde_json v1.0.109
         Compiling indexmap v2.0.0
         Compiling form_urlencoded v1.2.1
         Compiling idna v0.5.0
         Compiling regex-automata v0.4.3
         Compiling lexical-core v0.8.5
         Compiling strum v0.25.0
         Compiling pydantic-core v2.16.3 (C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a)
         Compiling itoa v1.0.8
         Compiling ryu v1.0.14
         Compiling regex v1.10.2
      error: failed to run custom build command for `pydantic-core v2.16.3 (C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a)`

      Caused by:
        process didn't exit successfully: `C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\target\release\build\pydantic-core-8ed60eb41c36f034\build-script-build` (exit code: 101)
        --- stdout
        cargo:rustc-cfg=Py_3_6
        cargo:rustc-cfg=Py_3_7
        cargo:rustc-cfg=Py_3_8
        cargo:rustc-cfg=Py_3_9
        cargo:rustc-cfg=Py_3_10
        cargo:rustc-cfg=Py_3_11
        cargo:rustc-cfg=Py_3_12
        cargo:rustc-cfg=Py_3_13
        cargo:rerun-if-changed=python/pydantic_core/core_schema.py
        cargo:rerun-if-changed=generate_self_schema.py

        --- stderr
        Traceback (most recent call last):
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 192, in eval_forward_ref
            return type_._evaluate(core_schema.__dict__, None, set())
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 240, in <module>
            main()
            ~~~~^^
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 210, in main
            value = get_schema(s, definitions)
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 54, in get_schema
            return type_dict_schema(obj, definitions)
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 152, in type_dict_schema
            field_type = eval_forward_ref(field_type)
          File "C:\Users\Neks (NB)\AppData\Local\Temp\pip-install-b27m7afd\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\generate_self_schema.py", line 195, in eval_forward_ref
            return type_._evaluate(core_schema.__dict__, None)
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
        thread 'main' panicked at build.rs:29:9:
        generate_self_schema.py failed with exit code: 1
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      рџ’Ґ maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "C:\\Users\\Neks (NB)\\AppData\\Local\\Temp\\pip-install-b27m7afd\\pydantic-core_cf8128faa4844b879f1d7954c9addc7a\\Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\PortableSort\\NotPixel-Yarmolenko\\notpixel\\venv\\Scripts\\python.exe', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pydantic_core
Failed to build pydantic_core
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pydantic_core)

(venv) C:\PortableSort\NotPixel-Yarmolenko\notpixel>pip install pydantic-core
Requirement already satisfied: pydantic-core in c:\portablesort\notpixel-yarmolenko\notpixel\venv\lib\site-packages (2.25.0)
Requirement already satisfied: typing-extensions!=4.7.0,>=4.6.0 in c:\portablesort\notpixel-yarmolenko\notpixel\venv\lib\site-packages (from pydantic-core) (4.12.2)`
```

![изображение_2024-10-27_134518897](https://github.com/user-attachments/assets/e779b181-3c35-43e0-ae81-0480a7fd19fa)

**Comment by Nekspsy** [comment]
Its works now, close or delete issue please ;)
